NotificationFunction:
  Type: AWS::Serverless::Function
  Properties:
    CodeUri: notification-service/
    Handler: src/handler.handler
    Runtime: nodejs22.x
    Timeout: 60
    MemorySize: 512
    Environment:
      Variables:
        DATABASE_URL: postgres://postgres:postgres@host.docker.internal:5432/notificationdb?sslmode=disable
        JWT_SECRET: autocare_secret_key
        REDIS_ADDR: host.docker.internal
        REDIS_PORT: "6379"
        BOOKING_EVENT_QUEUE: booking-events
        NOTIFICATION_EVENT_QUEUE: notification-events
        TWILIO_ACCOUNT_SID: OR4554160c3f7c537c1db7af633384274a
        TWILIO_AUTH_TOKEN: AC9911750eb3e63d2f61c94293ad848f1b
        TWILIO_FROM_NUMBER: "+14155238886"
        MSG91_AUTH_KEY: ""
        MSG91_SENDER_ID: ""
        RESEND_API_KEY: ""
        EMAIL_FROM: no-reply@autocare.local
    Events:
      NotificationRootApi:
        Type: Api
        Properties:
          Path: /notifications
          Method: ANY
      NotificationProxyApi:
        Type: Api
        Properties:
          Path: /notifications/{proxy+}
          Method: ANY